baseurl = "https://dbym4820.github.io/"
author = "Tomoki Aburatani"
title = "油谷知岐"
languageCode = "ja"
theme = "foundation-theme"
enableRobotsTXT = true
SectionPagesMenu = ["main", "social"]

[params.meta]
description = "大阪府立大学 人間社会システム科学研究科 現代システム科学専攻 知識情報システム学分野 油谷知岐"
keywords = "大阪府立大学　知識システム　人工知能　知的学習支援システム　教育システム情報学　学習科学　知識科学　学習態度　オントロジー"

[params.main]

[params.footer]
github = "https://github.com/dbym4820"
facebook = "https://www.facebook.com/tomoki.aburatani.1"
twitter = "https://twitter.com/dbym4820"
email = "aburatanitomoki[at]gmail.com"
labsite = "http://ks.mi.s.osakafu-u.ac.jp/"
kansailisp = "https://kansai-lisp-users.github.io/"
kansailispconnpass = "https://kansai-lisp-useres.connpass.com/"
aisl = "http://akibalab.info/"


[[menu.main]]
name = "Top"
url = "/"
weight = 1

[[menu.main]]
name = "Products"
url = "/products"
weight = 2

[[menu.main]]
name = "Others"
url = "/others"
weight = 3	
